= Native AsciiDoc File
:description: Build a sample Python app that interacts with the XRP Ledger.
:cta_text: Build an XRP Ledger-connected app
:filters: ["include_code"]
:html: get-started-using-python.html
:labels: ["Development"]
:showcase_icon: assets/img/logos/python.svg

This tutorial walks you through the basics of building a very simple XRP Ledger-connected application using https://github.com/XRPLF/xrpl-py[`xrpl-py`], a pure https://www.python.org[Python] library that makes it easy to interact with the XRP Ledger using native Python models and methods.

This tutorial is intended for beginners and should take no longer than 30 minutes to complete.

== Learning Goals

In this tutorial, you'll learn:

* The basic building blocks of XRP Ledger-based applications.
* How to connect to the XRP Ledger using `xrpl-py`.
* How to generate a wallet on the link:xrp-testnet-faucet.html[Testnet] using `xrpl-py`.
* How to use the `xrpl-py` library to look up information about an account on the XRP Ledger.
* How to put these steps together to create a simple Python app.

== Requirements

The `xrpl-py` library supports https://www.python.org/downloads/[Python 3.7] and later.

== Installation

The https://github.com/XRPLF/xrpl-py[`xrpl-py` library] is available on https://pypi.org/project/xrpl-py/[PyPI]. Install with `pip`:
// SPELLING_IGNORE: pypi

[source,py]
----
pip3 install xrpl-py
----

== Start Building

{% set n = cycler(* range(1,99)) %}

When you're working with the XRP Ledger, there are a few things you'll need to manage, whether you're adding XRP into your link:wallets.html[wallet], integrating with the link:decentralized-exchange.html[decentralized exchange], or link:issued-currencies.html[issuing tokens]. This tutorial walks you through basic patterns common to getting started with all of these use cases and provides sample code for implementing them.

Here are the basic steps you'll need to cover for almost any XRP Ledger project:

. <<1-connect-to-the-xrp-ledger,Connect to the XRP Ledger.>>
. <<2-generate-wallet,Generate a wallet.>>
. <<3-query-the-xrp-ledger,Query the XRP Ledger.>>

=== {{n.next()}}. Connect to the XRP Ledger

To make queries and submit transactions, you need to establish a connection to the XRP Ledger. To do this with `xrpl-py`, use the https://xrpl-py.readthedocs.io/en/latest/source/xrpl.clients.html[`xrp.clients` module]:

{{ include_code("_code-samples/get-started/py/get-acct-info.py", start_with="# Define the network client", end_before="# Create a wallet using the testnet faucet:", language="py") }}

==== Connect to the production XRP Ledger

The sample code in the previous section shows you how to connect to the Testnet, which is one of the available link:parallel-networks.html[parallel networks]. When you're ready to integrate with the production XRP Ledger, you'll need to connect to the Mainnet. You can do that in two ways:

* By link:install-rippled.html[installing the core server] (`rippled`) and running a node yourself. The core server connects to the Mainnet by default, but you can link:connect-your-rippled-to-the-xrp-test-net.html[change the configuration to use Testnet or Devnet]. link:the-rippled-server.html#reasons-to-run-your-own-server[There are good reasons to run your own core server]. If you run your own server, you can connect to it like so:

   from xrpl.clients import JsonRpcClient
   JSON_RPC_URL = "http://localhost:5005/"
   client = JsonRpcClient(JSON_RPC_URL)
+
See the example https://github.com/ripple/rippled/blob/c0a0b79d2d483b318ce1d82e526bd53df83a4a2c/cfg/rippled-example.cfg#L1562[core server config file] for more information about default values.

* By using one of the available [public servers][]:

   from xrpl.clients import JsonRpcClient
   JSON_RPC_URL = "https://s2.ripple.com:51234/"
   client = JsonRpcClient(JSON_RPC_URL)

=== {{n.next()}}. Generate wallet

To store value and execute transactions on the XRP Ledger, you need to create a wallet: a link:cryptographic-keys.html#key-components[set of keys] and an link:accounts.html#addresses[address] that's been link:accounts.html#creating-accounts[funded with enough XRP] to meet the link:reserves.html[account reserve]. The address is the identifier of your account and you use the link:cryptographic-keys.html#private-key[private key] to sign transactions that you submit to the XRP Ledger.

For testing and development purposes, you can use the link:xrp-testnet-faucet.html[XRP Faucets] to generate keys and fund the account on the Testnet or Devnet. For production purposes, you should take care to store your keys and set up a link:set-up-secure-signing.html[secure signing method].

To make it easy to create a wallet on the Testnet, `xrpl-py` provides the https://xrpl-py.readthedocs.io/en/latest/source/xrpl.wallet.html#xrpl.wallet.generate_faucet_wallet[`generate_faucet_wallet`] method:

{{ include_code("_code-samples/get-started/py/get-acct-info.py", start_with="# Create a wallet using the testnet faucet:", end_before="# Create an account str from the wallet", language="py") }}

This method returns a https://xrpl-py.readthedocs.io/en/latest/source/xrpl.wallet.html#xrpl.wallet.Wallet[`Wallet` instance]:

[,py]
----
print(test_wallet)

# print output
public_key:: 022FA613294CD13FFEA759D0185007DBE763331910509EF8F1635B4F84FA08AEE3
private_key:: -HIDDEN-
classic_address: raaFKKmgf6CRZttTVABeTcsqzRQ51bNR6Q
----

==== Using the wallet

In this tutorial we only query details about the generated account from the XRP Ledger, but you can use the values in the `Wallet` instance to prepare, sign, and submit transactions with `xrpl-py`.

===== Prepare

To prepare the transaction:

{{ include_code("_code-samples/get-started/py/prepare-payment.py", start_with="# Prepare payment", end_before="# print prepared payment", language="py") }}

===== Sign

To sign the transaction:

{{ include_code("_code-samples/get-started/py/prepare-payment.py", start_with="# Sign the transaction", end_before="# Print signed tx", language="py") }}

===== Send

To send the transaction:

{{ include_code("_code-samples/get-started/py/prepare-payment.py", start_with="# Submit and send the transaction", end_before="# Print tx response", language="py") }}

===== Derive an X-address

You can use ``xrpl-py``'s https://xrpl-py.readthedocs.io/en/latest/source/xrpl.core.addresscodec.html[`xrpl.core.addresscodec`] module to derive an https://xrpaddress.info/[X-address] from the `Wallet.classic_address` field:

{{ include_code("_code-samples/get-started/py/get-acct-info.py", start_with="# Derive an x-address from the classic address:", end_before="# Look up info about your account", language="py") }}

The X-address format https://github.com/XRPLF/XRPL-Standards/issues/6[packs the address and destination tag] into a more user-friendly value.

=== {{n.next()}}. Query the XRP Ledger

You can query the XRP Ledger to get information about link:account-methods.html[a specific account], link:tx.html[a specific transaction], the state of a link:ledger-methods.html[current or a historical ledger], and link:path-and-order-book-methods.html[the XRP Ledger's decentralized exchange]. You need to make these queries, among other reasons, to look up account info to follow best practices for link:reliable-transaction-submission.html[reliable transaction submission].

Here, we'll use ``xrpl-py``'s https://xrpl-py.readthedocs.io/en/latest/source/xrpl.account.html[`xrpl.account`] module to look up information about the <<2-generate-wallet,wallet we generated>> in the previous step.

{{ include_code("_code-samples/get-started/py/get-acct-info.py", start_with="# Look up info about your account", language="py")  }}

=== {{n.next()}}. Putting it all together

Using these building blocks, we can create a simple Python app that:

. Generates a wallet on the Testnet.
. Connects to the XRP Ledger.
. Looks up and prints information about the account you created.

[,python]
----
{% include '_code-samples/get-started/py/get-acct-info.py' %}
----

To run the app, you can copy and paste the code into an editor or IDE and run it from there. Or you could download the file from the https://github.com/XRPLF/xrpl-dev-portal/tree/master/content/_code-samples/xrpl-py[XRP Ledger Dev Portal repo] and run it locally:

[source,sh]
----
git clone git@github.com:XRPLF/xrpl-dev-portal.git
cd xrpl-dev-portal/content/_code-samples/get-started/py/get-acct-info.py
python3 get-acct-info.py
----

You should see output similar to this example:

[source,sh]
----
Classic address:

 rnQLnSEA1YFMABnCMrkMWFKxnqW6sQ8EWk
X-address:

 T7dRN2ktZGYSTyEPWa9SyDevrwS5yDca4m7xfXTGM3bqff8
response.status:  ResponseStatus.SUCCESS
{
    "account_data": {
        "Account": "rnQLnSEA1YFMABnCMrkMWFKxnqW6sQ8EWk",
        "Balance": "1000000000",
        "Flags": 0,
        "LedgerEntryType": "AccountRoot",
        "OwnerCount": 0,
        "PreviousTxnID": "5A5203AFF41503539D11ADC41BE4185761C5B78B7ED382E6D001ADE83A59B8DC",
        "PreviousTxnLgrSeq": 16126889,
        "Sequence": 16126889,
        "index": "CAD0F7EF3AB91DA7A952E09D4AF62C943FC1EEE41BE926D632DDB34CAA2E0E8F"
    },
    "ledger_current_index": 16126890,
    "queue_data": {
        "txn_count": 0
    },
    "validated": false
}
----

==== Interpreting the response

The response fields that you want to inspect in most cases are:

* `account_data.Sequence` -- This is the sequence number of the next valid transaction for the account. You need to specify the sequence number when you prepare transactions. With `xrpl-py`, you can use the https://xrpl-py.readthedocs.io/en/latest/source/xrpl.account.html#xrpl.account.get_next_valid_seq_number[`get_next_valid_seq_number`] to get this automatically from the XRP Ledger. See an example of this usage in the project https://github.com/XRPLF/xrpl-py#serialize-and-sign-transactions[README].
* `account_data.Balance` -- This is the account's balance of [XRP, in drops][]. You can use this to confirm that you have enough XRP to send (if you're making a payment) and to meet the link:transaction-cost.html#current-transaction-cost[current transaction cost] for a given transaction.
* `validated` -- Indicates whether the returned data is from a link:ledgers.html#open-closed-and-validated-ledgers[validated ledger]. When inspecting transactions, it's important to confirm that link:finality-of-results.html[the results are final] before further processing the transaction. If `validated` is `true` then you know for sure the results won't change. For more information about best practices for transaction processing, see link:reliable-transaction-submission.html[Reliable Transaction Submission].

For a detailed description of every response field, see link:account_info.html#response-format[account_info].

== Keep on building

Now that you know how to use `xrpl-py` to connect to the XRP Ledger, generate a wallet, and look up information about an account, you can also use `xrpl-py` to:

* xref:get-started-using-python.adoc[Send XRP].
* xref:payment-system:payment-.adoc[].
